### ISSUE TITLE
minifyEnabled true and shrinkResources true in release build retrofit api's are not working

### ISSUE THREAD

**Issue by vimalcvs** [badbanii/RandomUserDatabase#1]
**minifyEnabled true** and **shrinkResources true** in release build **retrofit api's** are not working

**Comment by badbanii** [comment]
> **minifyEnabled true** and **shrinkResources true** in release build **retrofit api's** are not working

Are you sure? I'll take a look, thanks.

**Comment by badbanii** [comment]
Fixed.
